name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ExampleWebApp/ExampleWebApp.csproj
      - name: Build
        run: dotnet build ExampleWebApp/ExampleWebApp.csproj --no-restore --configuration Release
      - name: Test
        run: dotnet test ExampleWebApp.Tests/ExampleWebApp.Tests.csproj --no-build --verbosity normal
